USE ROLE ACCOUNTADMIN;

-- Create the `BOOKSHOP_ROLE` role
CREATE ROLE IF NOT EXISTS BOOKSHOP_ROLE;
GRANT ROLE BOOKSHOP_ROLE TO ROLE ACCOUNTADMIN;

-- Create the default warehouse if necessary
CREATE WAREHOUSE IF NOT EXISTS BOOKSHOP_WH;
GRANT OPERATE ON WAREHOUSE BOOKSHOP_WH TO ROLE BOOKSHOP_ROLE;

-- Create the `BOOKSHOP_USER` user and assign to role
CREATE USER IF NOT EXISTS BOOKSHOP_USER
  PASSWORD='BOOKSHOP_password_1'
  LOGIN_NAME='BOOKSHOP_USER'
  MUST_CHANGE_PASSWORD=FALSE
  DEFAULT_WAREHOUSE='BOOKSHOP_WH'
  DEFAULT_ROLE='BOOKSHOP_ROLE'
  DEFAULT_NAMESPACE='BOOKSHOP.RAW'
  COMMENT='DBT user used for data transformation';
GRANT ROLE BOOKSHOP_ROLE to USER BOOKSHOP_USER;

-- Create our database and schemas
CREATE DATABASE IF NOT EXISTS BOOKSHOP;
CREATE SCHEMA IF NOT EXISTS BOOKSHOP.RAW;
CREATE SCHEMA IF NOT EXISTS BOOKSHOP.STAGING;
CREATE SCHEMA IF NOT EXISTS BOOKSHOP.WAREHOUSE;
CREATE SCHEMA IF NOT EXISTS BOOKSHOP.MARTS;

-- Set up permissions to role `BOOKSHOP_ROLE`
GRANT ALL ON WAREHOUSE BOOKSHOP_WH TO ROLE BOOKSHOP_ROLE; 
GRANT ALL ON DATABASE BOOKSHOP to ROLE BOOKSHOP_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE BOOKSHOP to ROLE BOOKSHOP_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE BOOKSHOP to ROLE BOOKSHOP_ROLE;

GRANT ALL ON ALL TABLES IN SCHEMA BOOKSHOP.RAW to ROLE BOOKSHOP_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA BOOKSHOP.RAW to ROLE BOOKSHOP_ROLE;

GRANT ALL ON ALL TABLES IN SCHEMA BOOKSHOP.STAGING to ROLE BOOKSHOP_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA BOOKSHOP.STAGING to ROLE BOOKSHOP_ROLE;

GRANT ALL ON ALL TABLES IN SCHEMA BOOKSHOP.WAREHOUSE to ROLE BOOKSHOP_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA BOOKSHOP.WAREHOUSE to ROLE BOOKSHOP_ROLE;

GRANT ALL ON ALL TABLES IN SCHEMA BOOKSHOP.MARTS to ROLE BOOKSHOP_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA BOOKSHOP.MARTS to ROLE BOOKSHOP_ROLE;
